### PR TITLE
Add control of graph gravity

### PR DESCRIPTION
**Pull request by mrparalon**
I'm working on [issue 25](https://github.com/trashhalo/logseq-graph-analysis/issues/25)

I branched out from live-updates branch, because

1. It works faster
2. I didn't managed to deal with Promise graph in storage on main

In this draft control for gravity works. But for some reasons it graph bounces back to initial state. I can't figure it out. 

@trashhalo Could you please give me a hint where to dig?

P.S Maybe you merge [live updates](https://github.com/trashhalo/logseq-graph-analysis/pull/29)? I see no downsides here

### CODE REVIEW

**Comment by mrparalon** [comment]
I figured everything out, it working now.
@trashhalo could you review it pls?

**Comment by trashhalo** [comment]
@mrparalon do I need to merge the other one too? or are these seperate?

**Comment by mrparalon** [comment]
Those are separate.

This one add gravity and other visualisation settings.

[This](https://github.com/trashhalo/logseq-graph-analysis/pull/35) fix analitycs visualisations in live-updates branch.

Both of them a branched from live-updates, not from master. So maybe it will worth to merge [this](https://github.com/trashhalo/logseq-graph-analysis/pull/29) too

**Comment by trashhalo** [comment]
merged into https://github.com/trashhalo/logseq-graph-analysis/pull/36

**Pull request closed without merging**
