### PR TITLE
background & color

### PR DESCRIPTION
**Pull request by YU000jp**
For dark mode https://github.com/trashhalo/logseq-graph-analysis/issues/24
It's untested how it will turn out. I tried to fork the repository and create an executable file, but the GitHub Action workflow failed and I haven't been able to confirm if there are any issues. Please review it instead.

### CODE REVIEW

**Comment by mrparalon** [comment]
Have you tried to build it locally? 

I connected local version as [unpacked plugin](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69) and develop with `yarn dev`

**Comment by YU000jp** [comment]
@mrparalon 

I installed the environment using `yarn` on the command line and tried to run Vite with `yarn build` or `yarn dev`, but encountered errors with the plugin and couldn't use them. Since I'm not familiar with this plugin in detail, I would like someone who can successfully build the plugin to review it.

**Comment by mrparalon** [comment]
@YU000jp could you please share your yarn version `yarn -v` and `yarn dev` output?

**Comment by YU000jp** [comment]
`yarn -v` ; 1.22.19
`yarn dev` output
image

Logseq
image

**Comment by mrparalon** [comment]
Usually this error appears, if you have some internal errors in plugin, which break it. You could open dev console to check it.

**Pull request closed without merging**
